version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.8
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
